### ISSUE TITLE
All task.md in https://github.com/openlifescience-ai/Open-Medical-Reasoning-Tasks/tree/main/subject_specific_medical_tasks are empty

### ISSUE THREAD

**Issue by alexmanner** [openlifescience-ai/Open-Medical-Reasoning-Tasks#4]
All task.md in https://github.com/openlifescience-ai/Open-Medical-Reasoning-Tasks/tree/main/subject_specific_medical_tasks are empty. Or is this by design and your objective is to complete these by the wisdowm of the crowds?

**Comment by monk1337** [comment]
Thank you for pointing that out! The empty task.md files are not by design; they are placeholders that we intend to populate. 

The idea is indeed to leverage the "wisdom of the crowds" by inviting contributions from the community to help develop and refine these tasks. We believe that collective input will lead to more comprehensive and robust medical reasoning tasks.
